#name: Check step 2, Set up the Azure environment

# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run every time we push to the deploy-staging.yml file on the staging-workflow branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows

name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
      

      # Update README to close <details id=2>
      # and open <details id=3>
      # and set STEP to '3'
